apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: example
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/example:v0.1.0-aa1dcf5-dirty
  resources:
  - kind: Extension
    type: example
